### ISSUE TITLE
super confusing choice of name on pypi

### ISSUE THREAD

**Issue by manihamidi** [Peter-Slump/django-dynamic-fixtures#14]
there is another library called [`django-dynamic-fixture`](https://github.com/paulocheque/django-dynamic-fixture)  (i.e. singular) with a different import entry-point. 

Was wracking my brains for two hours trying to understand why `import django_dynamic_fixture` wasn't working....

**Comment by Peter-Slump** [comment]
I was not aware of that project at time of publishing. This package is too wide spread to simply change the name.
